### PR TITLE
Restore files in android and ios runtime tests

### PR DESCRIPTION
**Pull request by vhristov5555**
- Restore files in android and ios runtime tests
- Add the ability to restore files
- Reorganize tests after the restore
- Fix some tests

### CODE REVIEW

**Comment by vhristov5555** [comment]
run ci

**Comment by vhristov5555** [comment]
run ci

**Comment by vhristov5555** [comment]
run ci

**Comment by vhristov5555** [comment]
test

**Comment by vhristov5555** [comment]
run ci

**Comment by vhristov5555** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
